"""Add category field to table definitions

Revision ID: 2efb3377fd03
Revises: 5bcad291b574
Create Date: 2025-01-27 23:00:27.710607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2efb3377fd03'
down_revision: Union[str, None] = '5bcad291b574'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table_definitions', sa.Column('category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('table_definitions', 'category')

    # ### end Alembic commands ###
