"""Add Column created_at to all models

Revision ID: 5bcad291b574
Revises: d2c590379e2c
Create Date: 2025-01-06 22:44:19.560693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bcad291b574'
down_revision: Union[str, None] = 'd2c590379e2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_report')
    op.drop_table('beton_log')
    op.add_column('favorite_tables', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('table_definitions', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('user_tables', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('user_tables', 'created_at')
    op.drop_column('table_definitions', 'created_at')
    op.drop_column('favorite_tables', 'created_at')
    op.create_table('beton_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('s_s', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vendor', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('quality', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('count', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('unit', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('doc_num', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='beton_log_pkey')
    )
    op.create_table('daily_report',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('s_s', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('geliş_tarihi', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tedarikçi', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('proje', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('orijinal_İrsaliye', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('İrsaliye_tarihi', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('malzemenin_türkçe_tanımı', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('malzemenin_rusça_tanımı', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('miktar', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('birim', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('birim_fiyat', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('topla_tutar', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tutar_naklıyelı', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('maliyet_tipi', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mtf_numara', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sipariş_eden', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sertifika', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pasaport', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='daily_report_pkey')
    )
    # ### end Alembic commands ###
